/* eslint-disable @typescript-eslint/no-unused-expressions */
import {parseOCR} from '../../src/domain/parsers';import{analyzeTrip,titles}from'../../src/domain/calculator';import{DEFAULT_SETTINGS}from'../../src/domain/settings';import type{APIRequest,APIResponse}from'../../src/types';
interface Env{API_TOKEN?:string;DB?:{prepare(q:string):{bind(...v:unknown[]):{run():Promise<unknown>}}}}
interface Context{request:Request;env:Env}
const buckets=new Map<string,{n:number,t:number}>();const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer'};
const json=(body:APIResponse,status=200)=>new Response(JSON.stringify(body),{status,headers});
export const onRequestPost=async({request,env}:Context)=>{try{const ip=request.headers.get('cf-connecting-ip')||'local',now=Date.now(),b=buckets.get(ip);if(b&&now-b.t<60_000&&b.n>=30)return json({success:false,classification:'insufficient',title:'Demasiadas solicitudes',summary:'Espera un minuto e intenta de nuevo.'},429);b&&now-b.t<60_000?b.n++:buckets.set(ip,{n:1,t:now});
 const ct=request.headers.get('content-type')||'';let body:APIRequest;if(ct.includes('application/json'))body=await request.json() as APIRequest;else if(ct.includes('application/x-www-form-urlencoded')){const f=await request.formData();body={text:String(f.get('text')||''),platform:String(f.get('platform')||'auto') as APIRequest['platform'],deviceId:String(f.get('deviceId')||''),save:String(f.get('save'))==='true',token:String(f.get('token')||'')}}else return json({success:false,classification:'insufficient',title:'Formato no compatible',summary:'Usa JSON o formulario.'},415);
 const bearer=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!env.API_TOKEN||!(bearer===env.API_TOKEN||body.token===env.API_TOKEN))return json({success:false,classification:'insufficient',title:'No autorizado',summary:'Revisa el token del Atajo.'},401);if(typeof body.text!=='string'||!body.text.trim()||body.text.length>15_000)return json({success:false,classification:'insufficient',title:'Entrada inválida',summary:'El texto debe tener entre 1 y 15,000 caracteres.'},400);
 const parsed=parseOCR(body.text,body.platform||'auto'),analysis=analyzeTrip(parsed,DEFAULT_SETTINGS),m=analysis.metrics;const res:APIResponse={success:!!m,classification:analysis.classification,title:titles[analysis.classification],summary:m?`${m.netPerKm.toFixed(2)} MXN/km · ${m.netPerHour.toFixed(0)} MXN/h · Neto aprox. ${m.estimatedNetProfit.toFixed(0)} MXN`:'No pude detectar correctamente la tarifa, distancia o tiempo.',missingFields:analysis.missingFields,warnings:parsed.warnings,data:m?{platform:parsed.platform,offeredFare:parsed.offeredFare!,totalDistanceKm:m.totalDistanceKm,totalDurationMin:m.totalDurationMin,estimatedNetProfit:m.estimatedNetProfit,netPerKm:m.netPerKm,netPerHour:m.netPerHour,confidence:parsed.confidence}:undefined};
 if(body.save&&m&&env.DB)await env.DB.prepare('INSERT INTO analyses VALUES (?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),body.deviceId||null,parsed.platform,analysis.classification,parsed.offeredFare,m.totalDistanceKm,m.totalDurationMin,m.estimatedNetProfit,JSON.stringify({data:res.data,warnings:res.warnings}),new Date().toISOString()).run();
 if(new URL(request.url).searchParams.get('format')==='text')return new Response(`${res.title}\n${m?`${m.netPerKm.toFixed(2)} MXN/km · ${m.netPerHour.toFixed(0)} MXN/h\nNeto aprox.: ${m.estimatedNetProfit.toFixed(0)} MXN`:res.summary}`,{status:m?200:422,headers:{...headers,'content-type':'text/plain; charset=utf-8'}});return json(res,m?200:422)}catch{return json({success:false,classification:'insufficient',title:'Error de solicitud',summary:'No se pudo procesar el contenido.'},400)}};
export const onRequestOptions=()=>new Response(null,{status:204,headers:{'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'Authorization, Content-Type','access-control-max-age':'86400'}});
