/* eslint-disable @typescript-eslint/no-unused-expressions */
import {parseOCR} from '../../src/domain/parsers';import{analyzeTrip,titles}from'../../src/domain/calculator';import{DEFAULT_SETTINGS}from'../../src/domain/settings';import type{APIRequest,APIResponse}from'../../src/types';
interface Env{API_TOKEN?:string;API_TOKENS?:string;DB?:{prepare(q:string):{bind(...v:unknown[]):{run():Promise<unknown>;first<T>():Promise<T|null>}}}}
interface Context{request:Request;env:Env}
const buckets=new Map<string,{n:number,t:number}>();const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer'};
const json=(body:APIResponse,status=200)=>new Response(JSON.stringify(body),{status,headers});
export const onRequestPost=async({request,env}:Context)=>{try{const ip=request.headers.get('cf-connecting-ip')||'local',now=Date.now(),b=buckets.get(ip);if(b&&now-b.t<60_000&&b.n>=30)return json({success:false,classification:'insufficient',title:'Demasiadas solicitudes',summary:'Espera un minuto e intenta de nuevo.'},429);b&&now-b.t<60_000?b.n++:buckets.set(ip,{n:1,t:now});
 const ct=request.headers.get('content-type')||'';let body:APIRequest;if(ct.includes('application/json'))body=await request.json() as APIRequest;else if(ct.includes('application/x-www-form-urlencoded')){const f=await request.formData();body={text:String(f.get('text')||''),platform:String(f.get('platform')||'auto') as APIRequest['platform'],deviceId:String(f.get('deviceId')||f.get('deviceID')||f.get('device_id')||f.get('deviceid')||''),save:String(f.get('save'))==='true',token:String(f.get('token')||'')}}else return json({success:false,classification:'insufficient',title:'Formato no compatible',summary:'Usa JSON o formulario.'},415);
 body.deviceId=String(body.deviceId||body.deviceID||body.device_id||body.deviceid||'').trim();
 const bearer=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');const supplied=bearer||body.token||'',validTokens=[env.API_TOKEN,...(env.API_TOKENS||'').split(',')].filter(Boolean);if(!validTokens.length||!validTokens.includes(supplied))return json({success:false,classification:'insufficient',title:'No autorizado',summary:'Revisa el token del Atajo.'},401);if(typeof body.text!=='string'||!body.text.trim()||body.text.length>15_000)return json({success:false,classification:'insufficient',title:'Entrada inválida',summary:'El texto debe tener entre 1 y 15,000 caracteres.'},400);
 const parsed=parseOCR(body.text,body.platform||'auto');let calculationSettings=DEFAULT_SETTINGS,profileSynced=false;if(env.DB&&body.deviceId){const row=await env.DB.prepare('SELECT settings_json FROM device_settings WHERE device_id=?').bind(body.deviceId.slice(0,128)).first<{settings_json:string}>();if(row)try{profileSynced=true;const stored=JSON.parse(row.settings_json);calculationSettings={...DEFAULT_SETTINGS,...stored,thresholds:{...DEFAULT_SETTINGS.thresholds,...stored.thresholds}}}catch{/* usa valores predeterminados */}}const analysis=analyzeTrip(parsed,calculationSettings),m=analysis.metrics;const res:APIResponse={success:!!m,classification:analysis.classification,title:titles[analysis.classification],summary:m?`${m.totalDistanceKm.toFixed(1)} km · ${Math.round(m.totalDurationMin)} min · Ganancia neta aprox. ${m.estimatedNetProfit.toFixed(0)} MXN`:'No pude detectar correctamente la tarifa, distancia o tiempo.',missingFields:analysis.missingFields,warnings:parsed.warnings,data:m?{platform:parsed.platform,offeredFare:parsed.offeredFare!,totalDistanceKm:m.totalDistanceKm,totalDurationMin:m.totalDurationMin,estimatedNetProfit:m.estimatedNetProfit,netPerKm:m.netPerKm,netPerHour:m.netPerHour,confidence:parsed.confidence}:undefined};
 let saved=false;if(m&&env.DB&&body.deviceId&&body.deviceId.length>=16&&body.save!==false&&body.save!=='false'){await env.DB.prepare('INSERT INTO analyses VALUES (?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),body.deviceId.slice(0,128),parsed.platform,analysis.classification,parsed.offeredFare,m.totalDistanceKm,m.totalDurationMin,m.estimatedNetProfit,JSON.stringify(analysis),new Date().toISOString()).run();saved=true}res.warnings=[...(res.warnings||[]),profileSynced?'Perfil sincronizado.':'Se usó la configuración predeterminada.',saved?'Historial guardado.':'Historial no guardado: revisa deviceId.'];
 if(new URL(request.url).searchParams.get('format')==='text')return new Response(`${res.title}\n${m?`${m.totalDistanceKm.toFixed(1)} km · ${Math.round(m.totalDurationMin)} min totales\nGanancia neta aprox.: ${m.estimatedNetProfit.toFixed(0)} MXN\n${m.netPerKm.toFixed(2)} MXN/km · ${m.netPerHour.toFixed(0)} MXN/h`:res.summary}`,{status:m?200:422,headers:{...headers,'content-type':'text/plain; charset=utf-8'}});return json(res,m?200:422)}catch{return json({success:false,classification:'insufficient',title:'Error de solicitud',summary:'No se pudo procesar el contenido.'},400)}};
export const onRequestOptions=()=>new Response(null,{status:204,headers:{'access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'Authorization, Content-Type','access-control-max-age':'86400'}});
