import type{VehicleSettings}from'../../src/types';import{DEFAULT_SETTINGS}from'../../src/domain/settings';
interface DB{prepare(q:string):{bind(...v:unknown[]):{run():Promise<unknown>;first<T>():Promise<T|null>}}}
interface Env{DB?:DB}interface Context{request:Request;env:Env}
const headers={'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};
const validCode=(v:string)=>v.length>=16&&v.length<=128;
const finite=(v:unknown,min:number,max:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
function sanitize(input:unknown):VehicleSettings|null{if(!input||typeof input!=='object')return null;const s=input as VehicleSettings;if(!finite(s.fuelPricePerLiter,0,500)||!finite(s.fuelEfficiencyKmPerLiter,.1,100)||!finite(s.maintenanceCostPerKm,0,100)||!finite(s.additionalCostPerKm,0,100)||!finite(s.contingencyPercent,0,100)||!finite(s.extraMinutes,0,120)||!finite(s.thresholds?.minNetPerKm,0,1000)||!finite(s.thresholds?.minNetPerHour,0,10000))return null;return{...DEFAULT_SETTINGS,...s,name:String(s.name||'').slice(0,80),country:String(s.country||'México').slice(0,40),currency:String(s.currency||'MXN').slice(0,8),fuelType:String(s.fuelType||'Gasolina').slice(0,30),includePickupDistance:Boolean(s.includePickupDistance),includePickupTime:Boolean(s.includePickupTime),syncCode:String(s.syncCode||'').slice(0,128),thresholds:{...DEFAULT_SETTINGS.thresholds,...s.thresholds}}}
export const onRequestPut=async({request,env}:Context)=>{if(!env.DB)return new Response(JSON.stringify({success:false,error:'D1 no configurado'}),{status:503,headers});const body=await request.json() as{deviceId?:string;settings?:unknown},deviceId=String(body.deviceId||'').trim(),settings=sanitize(body.settings);if(!validCode(deviceId)||!settings)return new Response(JSON.stringify({success:false,error:'Configuración inválida'}),{status:400,headers});await env.DB.prepare('INSERT INTO device_settings(device_id,settings_json,updated_at) VALUES(?,?,?) ON CONFLICT(device_id) DO UPDATE SET settings_json=excluded.settings_json,updated_at=excluded.updated_at').bind(deviceId,JSON.stringify(settings),new Date().toISOString()).run();return new Response(JSON.stringify({success:true}),{headers})};
export const onRequestGet=async({request,env}:Context)=>{const deviceId=new URL(request.url).searchParams.get('deviceId')||'';if(!env.DB||!validCode(deviceId))return new Response(JSON.stringify({success:false}),{status:400,headers});const row=await env.DB.prepare('SELECT settings_json FROM device_settings WHERE device_id=?').bind(deviceId).first<{settings_json:string}>();return new Response(JSON.stringify({success:true,settings:row?JSON.parse(row.settings_json):null}),{headers})};
